INSERT INTO USER_DETAILS (ID, NAME, BIRTH_DATE) VALUES (1001, 'TULSI KANT', CURRENT_DATE);
INSERT INTO USER_DETAILS (ID, NAME, BIRTH_DATE) VALUES (1002, 'RAUNIT SRIVASTAV', CURRENT_DATE);
INSERT INTO USER_DETAILS (ID, NAME, BIRTH_DATE) VALUES (1003, 'SATYA PRAKASH', CURRENT_DATE);


INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (100, 'LEARN AZURE', 1001);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (101, 'LEARN OPENSHIFT', 1001);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (102, 'LEARN SPRING', 1002);
INSERT INTO POST (ID, DESCRIPTION, USER_ID) VALUES (103, 'LEARN KUBERNETES', 1002);