INSERT INTO TODOS(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10001, 'Tulsi', 'Learn AWS', CURRENT_DATE(), FALSE);
INSERT INTO TODOS(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10002, 'Tulsi', 'Learn Docker', CURRENT_DATE(), FALSE);
INSERT INTO TODOS(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10003, 'Raunit', 'Learn GKE', CURRENT_DATE(), FALSE);
INSERT INTO TODOS(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10004, 'Raunit', 'Learn OCP', CURRENT_DATE(), FALSE);